### ISSUE TITLE
failed to initialize database

### ISSUE THREAD

**Issue by ChuckNorrison** [LightningTipBot/LightningTipBot#427]
With the current Version and with Release Version v0.5 i got this error on first start

> INFO[0000] Starting Dalle image generation. Worker: 2, Price: 1000 sat 
> INFO[2022-10-25 12:49:29] [PriceWatcher] Watcher started               
> 
> 2022/10/25 12:49:29 /home/lightningtipbot/LightningTipBot/internal/telegram/database.go:96
> [error] failed to initialize database, got error unable to open database file: no such file or directory
> ERRO[2022-10-25 12:49:29] Recovered panic:  Initialize orm failed.     
> goroutine 1 [running]:
> runtime/debug.Stack()
>         /usr/local/go/src/runtime/debug/stack.go:24 +0x88
> runtime/debug.PrintStack()
>         /usr/local/go/src/runtime/debug/stack.go:16 +0x20
> main.withRecovery()
>         /home/lightningtipbot/LightningTipBot/main.go:93 +0x98
> panic({0xc935c0, 0xf888d8})
>         /usr/local/go/src/runtime/panic.go:1038 +0x224
> github.com/LightningTipBot/LightningTipBot/internal/telegram.AutoMigration()
>         /home/lightningtipbot/LightningTipBot/internal/telegram/database.go:98 +0x628
> github.com/LightningTipBot/LightningTipBot/internal/telegram.NewBot()
>         /home/lightningtipbot/LightningTipBot/internal/telegram/bot.go:48 +0xe8
> main.main()
>         /home/lightningtipbot/LightningTipBot/main.go:40 +0x60
>

**Comment by ChuckNorrison** [comment]
This happens if the bot starts with insufficient permissions. Works for me
